### ISSUE TITLE
App doesn't run on android!

### ISSUE THREAD

**Issue by Farzin-Firoozi** [software-mansion-labs/reanimated-2-playground#12]
I installed node packages by running
`yarn`
then I ran
`npx react-native run-android`
then it resulted to this
![image](https://user-images.githubusercontent.com/52259209/93063656-d2752100-f68b-11ea-91de-c9a8dfb91601.png)

I think it is a problem caused by react-native-reanimated version 2
I tried using it on another project and this same error showed up.

any ideas?

**Comment by karol-bisztyga** [comment]
If you created an app with something like: `npx react-native init myapp`, please try something similar but without `npx`, like `react-native init myapp`. Also you can try: `rm -rf node_modules && yarn` - it is important to use `yarn` command, not `npm`

**Comment by Daavidaviid** [comment]
I've been trying to solve this issue on Android for a few days.
Complicated to solve because no logs appear, even with Flipper or adb

My configuration is : 

```
react-native: 0.63.3
react-native-reanimated: 2.0.0-alpha.8
hermes-engine: 0.5.2-rc1
```

And crash happens on launch, even with a basic App.tsx containing only a `<View>` and a `<Text>`.

**Comment by Daavidaviid** [comment]
Ok, So I found the issue, it was not linked to Reanimated.
But on Android, when using Hermes, the error message can be quite obscure.

So I was using, the javascript feature `underscores as separators ` and Hermes doesn't accept it yet : 

```
const DEFAULT_RADIUS = 10_000;
```

```
const DEFAULT_RADIUS = 10 * 1000;
```

Now it is working fine, finally !
