### ISSUE TITLE
Image not appear

### ISSUE THREAD

**Issue by yuliantosb** [software-mansion-labs/reanimated-2-playground#15]
Hello I just clone this repo and I try to run with ios emulator, but there's some issue I guess, the component `<Image />` don't want appear, but on android device it's appear.

// code
`<Image source={require('./assets/image.png')} />`

**on ios emulator**
![Simulator Screen Shot - iPhone 11 - 2020-09-30 at 20 10 15](https://user-images.githubusercontent.com/16331964/94704424-1ba2c180-036a-11eb-8c57-7190fa398e28.png)

**on android device**
![Screenshot_2020-09-30-20-08-21-975_com reanimated2playground](https://user-images.githubusercontent.com/16331964/94704507-2eb59180-036a-11eb-9b27-87a554bb46ce.jpg)

Sorry for my bad English

**Comment by karol-bisztyga** [comment]
Hey 👋 it does not seem to be related either to this repo or reanimated 2 itself(image isn't even an animated component), therefore I'm closing this for now.
Nevertheless [here](https://github.com/facebook/react-native/issues/29279#issuecomment-658244428) is a solution that may work in your case. Please try it, if it does not work and you really think this issue should be raised here, feel free to reopen.
