### ISSUE TITLE
Android error: "Tried to synchronously call function {fun} from a different thread"

### ISSUE THREAD

**Issue by alexfov** [software-mansion-labs/reanimated-2-playground#26]
1. Cloned reanimated-2-playground.
2. Run yarn
3. npm start + npm run android
4. Got error
Nothing else touched. This error related to useAnimatedStyle
![Screenshot_2020-12-09-01-07-33-234_com reanimated2playground](https://user-images.githubusercontent.com/39302602/101548578-2490be80-39bd-11eb-8864-1475deb87ea0.jpg)

**Comment by Cetger** [comment]
I have the same issue, any idea?

**Comment by Cetger** [comment]
> I have the same issue, any idea?

Hi guys, i dont know still reason of this issue but you dont care about it. If you are new on reanimated library as me. Just copy this code to Screen.js
`import Animated, {
  useSharedValue,
  withTiming,
  useAnimatedStyle,
  Easing,
} from 'react-native-reanimated';
import { View, Button, Text, StyleSheet } from 'react-native';
import React from 'react';

export default function AnimatedStyleUpdateExample(props) {
  const offset = useSharedValue(0);
  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ translateX: offset.value * 255 }],
    };
  });

  return (
    <>
      <Animated.View style={[{
        backgroundColor: "tomato",
        width: 200,
        height: 200,
      }, animatedStyles]} />
      <Button onPress={() => (offset.value = Math.random())} title="Move" />
    </>
  );
}
`
You can start to work by this.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
