### ISSUE TITLE
react-native-reanimated 2.3.1 is crashing on android

### ISSUE THREAD

**Issue by aomari** [software-mansion-labs/reanimated-2-playground#55]
React-native-reanimated is not working on android

```
 "react-native": "0.66.3",
 "react-native-reanimated": "^2.3.1",
```

and I have added the following lines to the Android

**MainApplication.java**
```
import com.facebook.react.bridge.JSIModulePackage;
import com.swmansion.reanimated.ReanimatedJSIModulePackage;

@Override
        protected JSIModulePackage getJSIModulePackage() {
            return new ReanimatedJSIModulePackage();
        }
```

**proguard.rules.pro**
```
# react-native-reanimated
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }
```

and when I try to run ```yarn run android``` get the following error screen, while this is not happening on IOS.

![Screenshot_2022-02-22-16-10-47-771_com aviv na dev](https://user-images.githubusercontent.com/4447140/155149775-6bc69432-d99e-4ee1-9843-58e6bf74f3f9.jpg)

**Comment by tomekzaw** [comment]
Hello! Please try running `adb reverse tcp:8081 tcp:8081` in your console and then reload the app.

**Comment by kacperkapusciak** [comment]
Closing as outdated issue

We've updated the repo to use the newest React Native & React Native Reanimated versions
