### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by hosseinmd** [software-mansion-labs/reanimated-2-playground#7]
I have an unknown error
<img width="303" alt="Screen Shot 2020-07-10 at 3 58 45 PM" src="https://user-images.githubusercontent.com/45505767/87149924-601c4500-c2c6-11ea-8624-fc6be8706bc2.png">

**Comment by ShaMan123** [comment]
+1
After commenting out `withTiming` the example works, so the BUG relays there

```diff
export default function AnimatedStyleUpdateExample(props) {

...
  const style = useAnimatedStyle(() => {
    return {
-       width: withTiming(randomWidth.value, config)
+      width: randomWidth.value
    };
  });


```

**Comment by hosseinmd** [comment]
Yes, I changed that and it works for me too
```js
    easing: Easing.inOut(Easing.ease),
```

**Comment by hosseinmd** [comment]
"react-native-reanimated": "2.0.0-alpha.3" don't work anyway

**Comment by hosseinmd** [comment]
Work Now.
https://github.com/software-mansion-labs/reanimated-2-playground/commit/71642dbe7bd96eb41df5b9f59d661ab15f6fc3f8

**Comment by kyle-ssg** [comment]
I'm still getting this on 2.0.0-alpha.4 though actually I think for people getting these issues, I think the issues may be around enabling hermes rather than this library.

**Comment by ShaMan123** [comment]
This is possible.
There was a PR that was merged with android config changes.

בתאריך יום א׳, 26 ביולי 2020, 17:57, מאת Kyle Johnson ‏<
notifications@github.com>:

**Comment by kyle-ssg** [comment]
Yeah it was Hermes in my instance, not this lib fix for me mentioned in https://github.com/facebook/hermes/issues/298#issuecomment-663999190. I think that any issues with node_modules / part of babel transpiling don't get reported correctly with Hermes.

**Comment by yasintz** [comment]
Hi,
I get this error.
![Screenshot_12](https://user-images.githubusercontent.com/36041339/93537414-1437ed00-f954-11ea-849f-7b0591acc5d9.png)
